-- ================================================
-- ISO 27001 ANNEX ITEMS DATA INSERTION
-- Inserts all ISO 27001 annex items with guidance
-- ================================================

-- Ensure UUID extension is enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ================================================
-- ISO 27001 ANNEX ITEMS DATA
-- ================================================

INSERT INTO "Iso27001AnnexItem" ("id", "itemId", "title", "description", "guidance", "orderIndex", "categoryId") VALUES
-- A.5: Organizational controls
(gen_random_uuid()::TEXT, 'A.5.1', 'Policies for information security', 'Management direction and support for information security via policies', 'Implement clear and effective measures for ''Policies for information security'' as part of organizational controls to keep information secure.', 1, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.2', 'Information security roles and responsibilities', 'Establishment of roles and responsibilities for information security', 'Implement clear and effective measures for ''Information security roles and responsibilities'' as part of organizational controls to keep information secure.', 2, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.3', 'Segregation of duties', 'Separating conflicting duties related to information security', 'Implement clear and effective measures for ''Segregation of duties'' as part of organizational controls to keep information secure.', 3, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.4', 'Management responsibilities', 'Assigning management responsibilities for information security', 'Implement clear and effective measures for ''Management responsibilities'' as part of organizational controls to keep information secure.', 4, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.5', 'Contact with authorities', 'Maintaining contact with relevant authorities', 'Implement clear and effective measures for ''Contact with authorities'' as part of organizational controls to keep information secure.', 5, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.6', 'Contact with special interest groups', 'Maintaining contact with special interest groups', 'Implement clear and effective measures for ''Contact with special interest groups'' as part of organizational controls to keep information secure.', 6, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.7', 'Threat intelligence', 'Gathering and analyzing threat intelligence', 'Implement clear and effective measures for ''Threat intelligence'' as part of organizational controls to keep information secure.', 7, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.8', 'Information security in project management', 'Integrating information security aspects into project management', 'Implement clear and effective measures for ''Information security in project management'' as part of organizational controls to keep information secure.', 8, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.9', 'Inventory of information and assets', 'Maintaining an inventory of information and information assets', 'Implement clear and effective measures for ''Inventory of information and assets'' as part of organizational controls to keep information secure.', 9, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.10', 'Acceptable use of information and assets', 'Defining rules for acceptable use of information and information assets', 'Implement clear and effective measures for ''Acceptable use of information and assets'' as part of organizational controls to keep information secure.', 10, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.11', 'Return of assets', 'Ensuring return of information assets', 'Implement clear and effective measures for ''Return of assets'' as part of organizational controls to keep information secure.', 11, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.12', 'Classification of information', 'Classifying information according to its value and sensitivity', 'Implement clear and effective measures for ''Classification of information'' as part of organizational controls to keep information secure.', 12, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.13', 'Labelling of information', 'Labelling information according to its classification', 'Implement clear and effective measures for ''Labelling of information'' as part of organizational controls to keep information secure.', 13, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.14', 'Handling of information', 'Handling information according to its classification', 'Implement clear and effective measures for ''Handling of information'' as part of organizational controls to keep information secure.', 14, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.15', 'Access control policy', 'Establishing access control policies', 'Implement clear and effective measures for ''Access control policy'' as part of organizational controls to keep information secure.', 15, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.16', 'Access to networks and network services', 'Controlling access to networks and network services', 'Implement clear and effective measures for ''Access to networks and network services'' as part of organizational controls to keep information secure.', 16, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.17', 'User registration and de-registration', 'Managing user registration and de-registration processes', 'Implement clear and effective measures for ''User registration and de-registration'' as part of organizational controls to keep information secure.', 17, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.18', 'Management of privileged access rights', 'Managing privileged access rights', 'Implement clear and effective measures for ''Management of privileged access rights'' as part of organizational controls to keep information secure.', 18, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.19', 'Management of secret authentication information', 'Managing secret authentication information', 'Implement clear and effective measures for ''Management of secret authentication information'' as part of organizational controls to keep information secure.', 19, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.20', 'Review of user access rights', 'Regular review of user access rights', 'Implement clear and effective measures for ''Review of user access rights'' as part of organizational controls to keep information secure.', 20, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.21', 'Removal or adjustment of access rights', 'Removing or adjusting access rights', 'Implement clear and effective measures for ''Removal or adjustment of access rights'' as part of organizational controls to keep information secure.', 21, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.22', 'Use of secret authentication information', 'Managing the use of secret authentication information', 'Implement clear and effective measures for ''Use of secret authentication information'' as part of organizational controls to keep information secure.', 22, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.23', 'Information security in supplier relationships', 'Managing information security in supplier relationships', 'Implement clear and effective measures for ''Information security in supplier relationships'' as part of organizational controls to keep information secure.', 23, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.24', 'Addressing information security within supplier agreements', 'Including information security requirements in supplier agreements', 'Implement clear and effective measures for ''Addressing information security within supplier agreements'' as part of organizational controls to keep information secure.', 24, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.25', 'Information and communication technology supply chain security', 'Ensuring security in ICT supply chain', 'Implement clear and effective measures for ''Information and communication technology supply chain security'' as part of organizational controls to keep information secure.', 25, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.26', 'Monitoring, review, and change management of supplier services', 'Monitoring and managing supplier services', 'Implement clear and effective measures for ''Monitoring, review, and change management of supplier services'' as part of organizational controls to keep information secure.', 26, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.27', 'Incident management responsibilities and procedures', 'Establishing incident management procedures', 'Implement clear and effective measures for ''Incident management responsibilities and procedures'' as part of organizational controls to keep information secure.', 27, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.28', 'Reporting information security events', 'Reporting information security events', 'Implement clear and effective measures for ''Reporting information security events'' as part of organizational controls to keep information secure.', 28, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.29', 'Reporting information security weaknesses', 'Reporting information security weaknesses', 'Implement clear and effective measures for ''Reporting information security weaknesses'' as part of organizational controls to keep information secure.', 29, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.30', 'Assessment and decision on information security events', 'Assessing and deciding on information security events', 'Implement clear and effective measures for ''Assessment and decision on information security events'' as part of organizational controls to keep information secure.', 30, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.31', 'Response to information security incidents', 'Responding to information security incidents', 'Implement clear and effective measures for ''Response to information security incidents'' as part of organizational controls to keep information secure.', 31, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.32', 'Learning from information security incidents', 'Learning from information security incidents', 'Implement clear and effective measures for ''Learning from information security incidents'' as part of organizational controls to keep information secure.', 32, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.33', 'Collection of evidence', 'Collecting evidence for incidents', 'Implement clear and effective measures for ''Collection of evidence'' as part of organizational controls to keep information secure.', 33, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.34', 'Business continuity planning for information security', 'Business continuity planning for information security', 'Implement clear and effective measures for ''Business continuity planning for information security'' as part of organizational controls to keep information secure.', 34, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.35', 'Redundancy of information processing facilities', 'Ensuring redundancy of information processing facilities', 'Implement clear and effective measures for ''Redundancy of information processing facilities'' as part of organizational controls to keep information secure.', 35, 'A.5'),
(gen_random_uuid()::TEXT, 'A.5.36', 'Documented operating procedures', 'Documenting operating procedures', 'Implement clear and effective measures for ''Documented operating procedures'' as part of organizational controls to keep information secure.', 36, 'A.5'),

-- A.6: People controls
(gen_random_uuid()::TEXT, 'A.6.1', 'Screening', 'Screening of personnel', 'Implement clear and effective measures for ''Screening'' as part of people controls to keep information secure.', 1, 'A.6'),
(gen_random_uuid()::TEXT, 'A.6.2', 'Terms and conditions of employment', 'Terms and conditions of employment', 'Implement clear and effective measures for ''Terms and conditions of employment'' as part of people controls to keep information secure.', 2, 'A.6'),
(gen_random_uuid()::TEXT, 'A.6.3', 'Information security awareness, education and training', 'Information security awareness, education and training', 'Implement clear and effective measures for ''Information security awareness, education and training'' as part of people controls to keep information secure.', 3, 'A.6'),
(gen_random_uuid()::TEXT, 'A.6.4', 'Disciplinary process', 'Disciplinary process for security violations', 'Implement clear and effective measures for ''Disciplinary process'' as part of people controls to keep information secure.', 4, 'A.6'),
(gen_random_uuid()::TEXT, 'A.6.5', 'Confidentiality or non-disclosure agreements', 'Confidentiality or non-disclosure agreements', 'Implement clear and effective measures for ''Confidentiality or non-disclosure agreements'' as part of people controls to keep information secure.', 5, 'A.6'),
(gen_random_uuid()::TEXT, 'A.6.6', 'Remote working', 'Remote working security measures', 'Implement clear and effective measures for ''Remote working'' as part of people controls to keep information secure.', 6, 'A.6'),
(gen_random_uuid()::TEXT, 'A.6.7', 'Termination or change of employment responsibilities', 'Termination or change of employment responsibilities', 'Implement clear and effective measures for ''Termination or change of employment responsibilities'' as part of people controls to keep information secure.', 7, 'A.6'),
(gen_random_uuid()::TEXT, 'A.6.8', 'User responsibilities', 'User responsibilities for information security', 'Implement clear and effective measures for ''User responsibilities'' as part of people controls to keep information secure.', 8, 'A.6'),

-- A.7: Physical controls
(gen_random_uuid()::TEXT, 'A.7.1', 'Physical security perimeters', 'Physical security perimeters', 'Implement clear and effective measures for ''Physical security perimeters'' as part of physical controls to keep information secure.', 1, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.2', 'Physical entry controls', 'Physical entry controls', 'Implement clear and effective measures for ''Physical entry controls'' as part of physical controls to keep information secure.', 2, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.3', 'Securing offices, rooms and facilities', 'Securing offices, rooms and facilities', 'Implement clear and effective measures for ''Securing offices, rooms and facilities'' as part of physical controls to keep information secure.', 3, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.4', 'Protecting against physical and environmental threats', 'Protecting against physical and environmental threats', 'Implement clear and effective measures for ''Protecting against physical and environmental threats'' as part of physical controls to keep information secure.', 4, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.5', 'Working in secure areas', 'Working in secure areas', 'Implement clear and effective measures for ''Working in secure areas'' as part of physical controls to keep information secure.', 5, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.6', 'Visitor access records', 'Visitor access records', 'Implement clear and effective measures for ''Visitor access records'' as part of physical controls to keep information secure.', 6, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.7', 'Delivery and loading areas', 'Delivery and loading areas', 'Implement clear and effective measures for ''Delivery and loading areas'' as part of physical controls to keep information secure.', 7, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.8', 'Equipment siting and protection', 'Equipment siting and protection', 'Implement clear and effective measures for ''Equipment siting and protection'' as part of physical controls to keep information secure.', 8, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.9', 'Supporting utilities', 'Supporting utilities', 'Implement clear and effective measures for ''Supporting utilities'' as part of physical controls to keep information secure.', 9, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.10', 'Cabling security', 'Cabling security', 'Implement clear and effective measures for ''Cabling security'' as part of physical controls to keep information secure.', 10, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.11', 'Equipment maintenance', 'Equipment maintenance', 'Implement clear and effective measures for ''Equipment maintenance'' as part of physical controls to keep information secure.', 11, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.12', 'Secure disposal or re-use of equipment', 'Secure disposal or re-use of equipment', 'Implement clear and effective measures for ''Secure disposal or re-use of equipment'' as part of physical controls to keep information secure.', 12, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.13', 'Removal of assets', 'Removal of assets', 'Implement clear and effective measures for ''Removal of assets'' as part of physical controls to keep information secure.', 13, 'A.7'),
(gen_random_uuid()::TEXT, 'A.7.14', 'Clear desk and clear screen policy', 'Clear desk and clear screen policy', 'Implement clear and effective measures for ''Clear desk and clear screen policy'' as part of physical controls to keep information secure.', 14, 'A.7'),

-- A.8: Technological controls
(gen_random_uuid()::TEXT, 'A.8.1', 'User endpoint devices', 'User endpoint devices', 'Implement clear and effective measures for ''User endpoint devices'' as part of technological controls to keep information secure.', 1, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.2', 'Privileged access rights', 'Privileged access rights', 'Implement clear and effective measures for ''Privileged access rights'' as part of technological controls to keep information secure.', 2, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.3', 'Access to source code', 'Access to source code', 'Implement clear and effective measures for ''Access to source code'' as part of technological controls to keep information secure.', 3, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.4', 'Change management', 'Change management', 'Implement clear and effective measures for ''Change management'' as part of technological controls to keep information secure.', 4, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.5', 'Capacity management', 'Capacity management', 'Implement clear and effective measures for ''Capacity management'' as part of technological controls to keep information secure.', 5, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.6', 'Development, testing and operational environments', 'Development, testing and operational environments', 'Implement clear and effective measures for ''Development, testing and operational environments'' as part of technological controls to keep information secure.', 6, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.7', 'Protection of test data', 'Protection of test data', 'Implement clear and effective measures for ''Protection of test data'' as part of technological controls to keep information secure.', 7, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.8', 'Logging and monitoring', 'Logging and monitoring', 'Implement clear and effective measures for ''Logging and monitoring'' as part of technological controls to keep information secure.', 8, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.9', 'Clock synchronization', 'Clock synchronization', 'Implement clear and effective measures for ''Clock synchronization'' as part of technological controls to keep information secure.', 9, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.10', 'Protection of log information', 'Protection of log information', 'Implement clear and effective measures for ''Protection of log information'' as part of technological controls to keep information secure.', 10, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.11', 'Administrator and operator logs', 'Administrator and operator logs', 'Implement clear and effective measures for ''Administrator and operator logs'' as part of technological controls to keep information secure.', 11, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.12', 'Fault logging', 'Fault logging', 'Implement clear and effective measures for ''Fault logging'' as part of technological controls to keep information secure.', 12, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.13', 'Cryptographic controls policy', 'Cryptographic controls policy', 'Implement clear and effective measures for ''Cryptographic controls policy'' as part of technological controls to keep information secure.', 13, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.14', 'Key management', 'Key management', 'Implement clear and effective measures for ''Key management'' as part of technological controls to keep information secure.', 14, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.15', 'Network controls', 'Network controls', 'Implement clear and effective measures for ''Network controls'' as part of technological controls to keep information secure.', 15, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.16', 'Security of network services', 'Security of network services', 'Implement clear and effective measures for ''Security of network services'' as part of technological controls to keep information secure.', 16, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.17', 'Segregation of networks', 'Segregation of networks', 'Implement clear and effective measures for ''Segregation of networks'' as part of technological controls to keep information secure.', 17, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.18', 'Use of network services', 'Use of network services', 'Implement clear and effective measures for ''Use of network services'' as part of technological controls to keep information secure.', 18, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.19', 'Web filtering', 'Web filtering', 'Implement clear and effective measures for ''Web filtering'' as part of technological controls to keep information secure.', 19, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.20', 'Cryptographic key usage', 'Cryptographic key usage', 'Implement clear and effective measures for ''Cryptographic key usage'' as part of technological controls to keep information secure.', 20, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.21', 'Backup', 'Backup', 'Implement clear and effective measures for ''Backup'' as part of technological controls to keep information secure.', 21, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.22', 'Information transfer policies and procedures', 'Information transfer policies and procedures', 'Implement clear and effective measures for ''Information transfer policies and procedures'' as part of technological controls to keep information secure.', 22, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.23', 'Electronic messaging', 'Electronic messaging', 'Implement clear and effective measures for ''Electronic messaging'' as part of technological controls to keep information secure.', 23, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.24', 'Confidentiality of information in networks', 'Confidentiality of information in networks', 'Implement clear and effective measures for ''Confidentiality of information in networks'' as part of technological controls to keep information secure.', 24, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.25', 'Security of system files', 'Security of system files', 'Implement clear and effective measures for ''Security of system files'' as part of technological controls to keep information secure.', 25, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.26', 'Malware protection', 'Malware protection', 'Implement clear and effective measures for ''Malware protection'' as part of technological controls to keep information secure.', 26, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.27', 'Technical vulnerability management', 'Technical vulnerability management', 'Implement clear and effective measures for ''Technical vulnerability management'' as part of technological controls to keep information secure.', 27, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.28', 'Configuration management', 'Configuration management', 'Implement clear and effective measures for ''Configuration management'' as part of technological controls to keep information secure.', 28, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.29', 'Monitoring of system use', 'Monitoring of system use', 'Implement clear and effective measures for ''Monitoring of system use'' as part of technological controls to keep information secure.', 29, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.30', 'Protection of application services', 'Protection of application services', 'Implement clear and effective measures for ''Protection of application services'' as part of technological controls to keep information secure.', 30, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.31', 'Data masking', 'Data masking', 'Implement clear and effective measures for ''Data masking'' as part of technological controls to keep information secure.', 31, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.32', 'Network service security audit', 'Network service security audit', 'Implement clear and effective measures for ''Network service security audit'' as part of technological controls to keep information secure.', 32, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.33', 'Network service security compliance', 'Network service security compliance', 'Implement clear and effective measures for ''Network service security compliance'' as part of technological controls to keep information secure.', 33, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.34', 'Network service security reporting', 'Network service security reporting', 'Implement clear and effective measures for ''Network service security reporting'' as part of technological controls to keep information secure.', 34, 'A.8'),
(gen_random_uuid()::TEXT, 'A.8.35', 'Network service security improvement', 'Network service security improvement', 'Implement clear and effective measures for ''Network service security improvement'' as part of technological controls to keep information secure.', 35, 'A.8')

ON CONFLICT ("itemId") DO UPDATE SET
"title" = EXCLUDED."title",
"description" = EXCLUDED."description",
"guidance" = EXCLUDED."guidance",
"orderIndex" = EXCLUDED."orderIndex",
"categoryId" = EXCLUDED."categoryId";
