import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@fontsource/raleway/700.css";
import "@fontsource/raleway/600.css";
import "@fontsource/source-sans-pro/400.css";
import "@fontsource/source-sans-pro/600.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-body antialiased`}
        style={{ fontFamily: '"Source Sans Pro", Arial, Helvetica, sans-serif' }}
      >
        <style>{`
          .font-heading, h1, h2, h3, h4 {
            font-family: 'Raleway', Arial, Helvetica, sans-serif;
            font-weight: 700;
          }
          .font-body, body, p, span, label, input, textarea, button {
            font-family: 'Source Sans Pro', Arial, Helvetica, sans-serif;
            font-weight: 400;
          }
        `}</style>
        {children}
      </body>
    </html>
  );
}
