import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Lora, Nunito, Merriweather } from "next/font/google";
import "./globals.css";
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const lora = Lora({
  subsets: ["latin"],
  variable: "--font-lora",
});

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
  weight: ["600"],
});

const merriweather = Merriweather({
  subsets: ["latin"],
  variable: "--font-merriweather",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function MenuIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg {...props} xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${lora.variable} ${nunito.variable} ${merriweather.variable} antialiased`}
        suppressHydrationWarning
      >
        <header className="sticky top-0 flex h-16 w-full shrink-0 items-center px-4 md:px-8 bg-white/95 backdrop-blur-md border-b border-gray-200/60 shadow-sm z-50">
          {/* Mobile menu */}
          <Sheet>
            <SheetTrigger asChild>
              <Button variant="outline" size="icon" className="lg:hidden mr-4 border-gray-300 hover:bg-gray-50 hover:border-gray-400 transition-all duration-200">
                <MenuIcon className="h-5 w-5 text-gray-600" />
                <span className="sr-only">Toggle navigation menu</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="left" className="w-72 bg-white/95 backdrop-blur-md border-r border-gray-200/60">
              <div className="font-bold text-xl mb-8 text-gray-900 tracking-tight">LOGO - QUBE</div>
              <nav className="grid gap-1">
                <Link href="/dashboard" className="flex items-center px-4 py-3 text-sm font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all duration-200 border-l-4 border-transparent hover:border-blue-500" prefetch={false}>
                  Portfolio Dashboard
                </Link>
                <Link href="/dashboard" className="flex items-center px-4 py-3 text-sm font-medium text-gray-700 hover:text-green-600 hover:bg-green-50 rounded-lg transition-all duration-200 border-l-4 border-transparent hover:border-green-500" prefetch={false}>
                  Use Cases
                </Link>
                <Link href="/dashboard/risks" className="flex items-center px-4 py-3 text-sm font-medium text-gray-700 hover:text-red-600 hover:bg-red-50 rounded-lg transition-all duration-200 border-l-4 border-transparent hover:border-red-500" prefetch={false}>
                  Risk Management
                </Link>
                <Link href="/dashboard/finops-dashboard" className="flex items-center px-4 py-3 text-sm font-medium text-gray-700 hover:text-purple-600 hover:bg-purple-50 rounded-lg transition-all duration-200 border-l-4 border-transparent hover:border-purple-500" prefetch={false}>
                  FinOps Dashboard
                </Link>
                <Link href="#" className="flex items-center px-4 py-3 text-sm font-medium text-gray-700 hover:text-orange-600 hover:bg-orange-50 rounded-lg transition-all duration-200 border-l-4 border-transparent hover:border-orange-500" prefetch={false}>
                  Policy Center
                </Link>
              </nav>
            </SheetContent>
          </Sheet>
          
          {/* Brand */}
          <div className="flex items-center gap-2 mr-8 select-none">
            <img src="https://blfsawovozyywndoiicu.supabase.co/storage/v1/object/sign/company/sharpened_logo_transparent.png?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV81MjUwODc5My03NTY4LTQ5ZWYtOTJlMS1lYmU4MmM1YTUwYzQiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJjb21wYW55L3NoYXJwZW5lZF9sb2dvX3RyYW5zcGFyZW50LnBuZyIsImlhdCI6MTc1MTI5NzE1NCwiZXhwIjoyMDY2NjU3MTU0fQ.wWxWelTaht2N75Nv9yr6vidPmBNhL41oDyPthQBKXiY" alt="QZen AI Logo" className="h-8 w-8 md:h-10 md:w-10" style={{minWidth:'2rem'}} />
            <span className="text-xl md:text-2xl font-extrabold bg-gradient-to-r from-blue-500 via-purple-500 to-fuchsia-500 bg-clip-text text-transparent tracking-tight" style={{letterSpacing: '-0.01em'}}>QZen AI</span>
          </div>
          
          {/* Desktop nav */}
          <nav className="ml-auto hidden lg:flex items-center gap-1">
            <Link href="/dashboard" className="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-blue-600 hover:bg-blue-50 rounded-lg transition-all duration-200 border-b-2 border-transparent hover:border-blue-500" prefetch={false}>
              Portfolio Dashboard
            </Link>
            <Link href="/dashboard" className="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-green-600 hover:bg-green-50 rounded-lg transition-all duration-200 border-b-2 border-transparent hover:border-green-500" prefetch={false}>
              Use Cases
            </Link>
            <Link href="/dashboard/risks" className="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-red-600 hover:bg-red-50 rounded-lg transition-all duration-200 border-b-2 border-transparent hover:border-red-500" prefetch={false}>
              Risk Management
            </Link>
            <Link href="/dashboard/finops-dashboard" className="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-purple-600 hover:bg-purple-50 rounded-lg transition-all duration-200 border-b-2 border-transparent hover:border-purple-500" prefetch={false}>
              FinOps Dashboard
            </Link>
            <Link href="#" className="inline-flex items-center px-4 py-2 text-sm font-medium text-gray-700 hover:text-orange-600 hover:bg-orange-50 rounded-lg transition-all duration-200 border-b-2 border-transparent hover:border-orange-500" prefetch={false}>
              Policy Center
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
